# Generated by Django 5.0.6 on 2024-07-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watchlist',
            new_name='user',
        ),
    ]
